# Generated by Django 5.0.7 on 2024-08-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_package_description_comment_delete_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
