# Generated by Django 5.0.7 on 2024-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionbuy',
            options={'ordering': ['purchased']},
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
